export const EXCEL_COLUMNS: Record<string, string[]> = {
  poHeader: [
    "Indent No",
    "Vendor Code",
    "Order Date",
    "Vaue Rs",
    "Inspection Agency Type",
    "Inspector Code",
    "InspectionSiteCode",
    "Remarks",
    "Quote Key",
    "Selected Quote Date",
    "Date Time Approved",
    "Approved By",
    "Type Closing",
    "Date cloded",
    "Packing Instructions",
    "Despatch Instructions",
    "Inspection Instructions",
    "Station Code",
    "Remarks1",
    "Name",
    "City",
    "State"
  ], 

  poDetail: [
    "Indent No",
    "Vendor Code",
    "Order Date",
    "Order Line No",
    "Item Code",
    "Consignee Code",
    "OrderLineDRB",
    "Specs",
    "Qty",
    "UniCostcc",
    "Pilot SampleDRb",
    "MIQPQty",
    "Pack Type",
    "Station Code",
    "ReReferenced Item Code"
  ],

  itemDetail: [
    "Indent No",
    "Vendor Code",
    "Order Date",
    "Order Line No",
    "Item Code",
    "Section Head",
    "Description",
    "Country",
    "Item Deno",
    "Shelf Life",
    "CRP Category",
    "VEDC Category",
    "ABC Category"
  ],
};
